[package]
description = "Maker on-chain OTC market."
name = "parity-makerotc"
version = "0.1.3"
license = "?"
authors = ["MakerDAO"]

[dependencies]
parity-webapp = { git = "https://github.com/ethcore/parity-webapp.git", version = "0.2" }
